services:
  db:
    image: postgres:14.18
    container_name: midogshop_db
    restart: always
    environment:
      POSTGRES_USER: mango
      POSTGRES_PASSWORD: mango
      POSTGRES_DB: midogshop
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  web:
    build: .
    container_name: midogshop_web
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - DB_HOST=db
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
