# Generated by Django 5.2.1 on 2025-05-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
        migrations.RenameModel(
            old_name='OrderShippings',
            new_name='OrderShipping',
        ),
        migrations.RenameModel(
            old_name='PaymentMethods',
            new_name='PaymentMethod',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='ProductOptions',
            new_name='ProductOption',
        ),
        migrations.RenameModel(
            old_name='ProductValues',
            new_name='ProductValue',
        ),
        migrations.RenameModel(
            old_name='ProductVariants',
            new_name='ProductVariant',
        ),
        migrations.RenameModel(
            old_name='ShippingMethods',
            new_name='ShippingMethod',
        ),
        migrations.AlterModelTable(
            name='orderaddresshome',
            table='order_address_home',
        ),
        migrations.AlterModelTable(
            name='ordershipping',
            table='order_shippings',
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table='payment_methods',
        ),
        migrations.AlterModelTable(
            name='shippingmethod',
            table='shipping_methods',
        ),
    ]
