# Generated by Django 5.2.1 on 2025-05-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admins',
            table='admins',
        ),
        migrations.AlterModelTable(
            name='categories',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='customeraddresshome',
            table='customer_address_home',
        ),
        migrations.AlterModelTable(
            name='customers',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='productoptions',
            table='product_options',
        ),
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
        migrations.AlterModelTable(
            name='productvalues',
            table='product_values',
        ),
        migrations.AlterModelTable(
            name='productvariants',
            table='product_variants',
        ),
        migrations.AlterModelTable(
            name='variantvaluemap',
            table='variant_value_map',
        ),
    ]
