# Generated by Django 5.2.1 on 2025-05-28 07:59

from django.db import migrations
from django.db.models import Q


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    customer, _ = Group.objects.get_or_create(name='Customer')
    staff, _ = Group.objects.get_or_create(name='Staff')
    manager, _ = Group.objects.get_or_create(name='Manager')

    staff_perms = Permission.objects.filter(codename__icontains='order')
    staff.permissions.set(staff_perms)

    manager_perms = Permission.objects.filter(
        Q(codename__icontains='order') |
        Q(codename__icontains='product') |
        Q(codename__icontains='category') |
        Q(codename__icontains='shipping') |
        Q(codename__icontains='payment')
    )
    manager.permissions.set(manager_perms)

def create_category(apps, schema_editor):
    Category = apps.get_model('api', 'Category')
    for name, display_name in [('food', '飼料'), ('snack', '零食'), ('canned', '罐罐'), ('health', '保健食品'), ('beauty', '美容用品'), 
                               ('home', '居家用品'), ('outdoor', '外出用品'), ('toilet', '廁所用品'), ('toy', '玩具')]:
        Category.objects.get_or_create(name=name, display_name=display_name)
        
def create_product_option(apps, schema_editor):
    ProductOption = apps.get_model('api', 'ProductOption')
    for name, display_name in [('color', '顏色'), ('size', '尺寸')]:
        ProductOption.objects.get_or_create(name=name, display_name=display_name)
    
def create_shipping_method(apps, schema_editor):
    ShippingMethod = apps.get_model('api', 'ShippingMethod')
    for name, display_name in [('home', '宅配'), ('store', '到店自取')]:
        ShippingMethod.objects.get_or_create(name=name, display_name=display_name)
        
def create_payment_method(apps, schema_editor):
    PaymentMethod = apps.get_model('api', 'PaymentMethod')
    for name, display_name in [('cash', '現金付款'), ('credit', '信用卡付款')]:
        PaymentMethod.objects.get_or_create(name=name, display_name=display_name)
        

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_product_option, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_shipping_method, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_payment_method, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_groups, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_category, reverse_code=migrations.RunPython.noop)
    ]
