# Generated by Django 5.2.1 on 2025-05-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_admins_table_alter_categories_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='customeraddresshome',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productvalues',
            old_name='option_id',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='productvariants',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='variantvaluemap',
            old_name='variant_id',
            new_name='variant',
        ),
    ]
