# Generated by Django 5.2.1 on 2025-05-26 12:00

from django.db import migrations
from django.db.models import Q


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    customer, _ = Group.objects.get_or_create(name='Customer')
    staff, _ = Group.objects.get_or_create(name='Staff')
    manager, _ = Group.objects.get_or_create(name='Manager')

    staff_perms = Permission.objects.filter(codename__icontains='order')
    staff.permissions.set(staff_perms)

    manager_perms = Permission.objects.filter(
        Q(codename__icontains='order') |
        Q(codename__icontains='product') |
        Q(codename__icontains='category')
    )
    manager.permissions.set(manager_perms)
    
def create_category(apps, schema_editor):
    Category = apps.get_model('api', 'Category')
    for name in ['飼料', '零食', '罐罐', '保健食品', '美容用品', '居家用品', '外出用品', '廁所用品', '玩具']:
        Category.objects.get_or_create(name=name)
        
    
class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.RunPython(create_groups),
        migrations.RunPython(create_category),
    ]
