# Generated by Django 5.2.1 on 2025-05-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20250526_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usage_type',
            field=models.CharField(choices=[('DOG', '狗'), ('CAT', '貓'), ('GENERAL', '通用')], default=(
                'GENERAL', '通用'), max_length=50),
        ),
    ]
