# Generated by Django 5.2.1 on 2025-05-27 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_usage_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantvaluemap',
            old_name='value_id',
            new_name='value',
        ),
    ]
