# Generated by Django 5.2.1 on 2025-05-27 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_value_id_variantvaluemap_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='value',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.productvalue'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VariantValueMap',
        ),
    ]
